apiVersion: v2
name: pagopareceiptpdfdatastore
description: Microservice description
type: application
version: 0.138.0
appVersion: 1.16.4
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
