apiVersion: v2
name: pagopareceiptpdfdatastore
description: Microservice description
type: application
version: 0.143.0
appVersion: 1.16.5-1-PAGOPA-3343-cart
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-datastore
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-datastore-helpdesk
