apiVersion: v2
name: pagopareceiptpdfdatastore
description: Microservice description
type: application
version: 0.137.0
appVersion: 1.16.3-1-update-cart-entity-for-remote-content
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
