apiVersion: v2
name: pagopareceiptpdfdatastore
description: Microservice description
type: application
version: 0.133.0
appVersion: 1.16.0-1-PAGOPA-3371-ipg-147-cart-datastore-configurare-log-su-kibana
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
