apiVersion: v2
name: pagopareceiptpdfdatastore
description: Microservice description
type: application
version: 0.149.0
appVersion: 1.17.4
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-receipt-pdf-datastore-helpdesk
